services:
  mariadb:
    image: mariadb:11.4
    container_name: app_mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: your-db-password
      MARIADB_DATABASE: your-db-name
      MARIADB_USER: your-db-user
      MARIADB_PASSWORD: your-db-password

    ports:
      - "3307:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./backend/db/init:/docker-entrypoint-initdb.d:ro

volumes:
  mariadb_data: